package server;

import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.*;

/**
 * Lightweight HTTP-like server for admin dashboard.
 * Supports simple requests such as: GET /results
 * Responds with a plain-text report generated by ResultManager.
 */
public class AdminHTTPServer {
    public static int PORT = 8080;

    public static void main(String[] args) {
        // allow overriding port via first command-line argument
        if (args.length >= 1) {
            try { PORT = Integer.parseInt(args[0]); } catch (NumberFormatException ignored) {}
        }
        ExecutorService pool = Executors.newCachedThreadPool();
        ServerSocket serverSocket = null;
        try {
            serverSocket = new ServerSocket(PORT);
            System.out.println("AdminHTTPServer listening on port " + PORT);
            System.out.flush();
            while (true) {
                Socket client = serverSocket.accept();
                pool.execute(new AdminHandler(client));
            }
        } catch (IOException e) {
            System.err.println("AdminHTTPServer error: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (serverSocket != null && !serverSocket.isClosed()) {
                    serverSocket.close();
                }
            } catch (IOException ignored) {}
            pool.shutdown();
        }
    }

    static class AdminHandler implements Runnable {
        private Socket socket;

        public AdminHandler(Socket socket) {
            this.socket = socket;
        }

        @Override
        public void run() {
            String clientAddr = socket.getRemoteSocketAddress().toString();
            try (BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream(), StandardCharsets.UTF_8));
                 OutputStream out = socket.getOutputStream()) {

                // Read request line
                String requestLine = in.readLine();
                if (requestLine == null || requestLine.isEmpty()) {
                    socket.close();
                    return;
                }

                System.out.println("[AdminHTTPServer] Request from " + clientAddr + ": " + requestLine);

                // Consume remaining header lines until blank line (simple HTTP-like)
                String line;
                while ((line = in.readLine()) != null && !line.isEmpty()) {
                    // simply skip headers for this lightweight protocol
                }

                // Parse simple GET/POST request
                String[] parts = requestLine.split(" ");
                String method = parts.length >= 1 ? parts[0].toUpperCase() : "GET";
                if (parts.length >= 2) {
                    String path = parts[1];

                    // Serve dashboard and static files from admin/ directory
                    if ("/".equals(path) || "/dashboard.html".equalsIgnoreCase(path) || path.startsWith("/admin/")) {
                        String rel = path.equals("/") ? "dashboard.html" : path.substring(1);
                        Path file = Paths.get("admin", rel.replaceFirst("^admin/", ""));
                        if (Files.exists(file) && !Files.isDirectory(file)) {
                            byte[] data = Files.readAllBytes(file);
                            String contentType = guessContentType(file.toString());
                            writeHttpResponseBytes(out, 200, "OK", contentType, data);
                        } else {
                            String body = "Not Found: " + path + "\n";
                            writeHttpResponse(out, 404, "Not Found", "text/plain; charset=utf-8", body);
                        }

                    // API: /api/status (exam state JSON)
                    } else if ("/api/status".equalsIgnoreCase(path)) {
                        String body = ExamState.getExamProgressJson();
                        writeHttpResponse(out, 200, "OK", "application/json; charset=utf-8", body);

                    // API: /api/students (connected students count)
                    } else if ("/api/students".equalsIgnoreCase(path)) {
                        String body = "{\"connected\": " + ExamState.getConnectedStudents() + 
                                     ", \"registered\": " + server.UserManager.getRegisteredUserCount() + "}";
                        writeHttpResponse(out, 200, "OK", "application/json; charset=utf-8", body);

                    // API: /api/results (same as /results, JSON format)
                    } else if ("/api/results".equalsIgnoreCase(path)) {
                        String body = ResultManager.getResultsReportJson();
                        writeHttpResponse(out, 200, "OK", "application/json; charset=utf-8", body);

                    // Existing API: /results (text report)
                    } else if ("/results".equalsIgnoreCase(path)) {
                        String body = ResultManager.getResultsReport();
                        writeHttpResponse(out, 200, "OK", "text/plain; charset=utf-8", body);

                    // API: POST /api/start
                    } else if ("POST".equalsIgnoreCase(method) && "/api/start".equalsIgnoreCase(path)) {
                        ExamServer.startExamProgrammatically();
                        String body = "{\"status\":\"success\",\"message\":\"Exam started\"}";
                        writeHttpResponse(out, 200, "OK", "application/json; charset=utf-8", body);
                        System.out.println("[AdminHTTPServer] Exam started via API");

                    // API: POST /api/stop
                    } else if ("POST".equalsIgnoreCase(method) && "/api/stop".equalsIgnoreCase(path)) {
                        ExamState.setState("STOPPED");
                        String body = "{\"status\":\"success\",\"message\":\"Exam stopped\"}";
                        writeHttpResponse(out, 200, "OK", "application/json; charset=utf-8", body);
                        System.out.println("[AdminHTTPServer] Exam stopped via API");

                    } else {
                        String body = "Not Found: " + path + "\n";
                        writeHttpResponse(out, 404, "Not Found", "text/plain; charset=utf-8", body);
                    }
                } else {
                    String body = "Bad Request\n";
                    writeHttpResponse(out, 400, "Bad Request", "text/plain; charset=utf-8", body);
                }

                System.out.println("[AdminHTTPServer] Response sent to " + clientAddr);

            } catch (IOException e) {
                System.err.println("[AdminHTTPServer] Error handling " + clientAddr + ": " + e.getMessage());
            } finally {
                try { socket.close(); } catch (IOException ignored) {}
            }
        }

        private void writeHttpResponse(OutputStream out, int statusCode, String statusText, String contentType, String body) throws IOException {
            byte[] bodyBytes = body.getBytes(StandardCharsets.UTF_8);
            PrintWriter pw = new PrintWriter(new OutputStreamWriter(out, StandardCharsets.UTF_8), true);
            pw.print("HTTP/1.1 " + statusCode + " " + statusText + "\r\n");
            pw.print("Content-Type: " + contentType + "\r\n");
            pw.print("Content-Length: " + bodyBytes.length + "\r\n");
            pw.print("Access-Control-Allow-Origin: *\r\n");
            pw.print("Access-Control-Allow-Methods: GET, POST, OPTIONS\r\n");
            pw.print("Connection: close\r\n");
            pw.print("\r\n");
            pw.flush();
            out.write(bodyBytes);
            out.flush();
        }

        private void writeHttpResponseBytes(OutputStream out, int statusCode, String statusText, String contentType, byte[] data) throws IOException {
            PrintWriter pw = new PrintWriter(new OutputStreamWriter(out, StandardCharsets.UTF_8), true);
            pw.print("HTTP/1.1 " + statusCode + " " + statusText + "\r\n");
            pw.print("Content-Type: " + contentType + "\r\n");
            pw.print("Content-Length: " + data.length + "\r\n");
            pw.print("Access-Control-Allow-Origin: *\r\n");
            pw.print("Access-Control-Allow-Methods: GET, POST, OPTIONS\r\n");
            pw.print("Connection: close\r\n");
            pw.print("\r\n");
            pw.flush();
            out.write(data);
            out.flush();
        }

        private String guessContentType(String filename) {
            String lower = filename.toLowerCase();
            if (lower.endsWith(".html") || lower.endsWith(".htm")) return "text/html; charset=utf-8";
            if (lower.endsWith(".css")) return "text/css; charset=utf-8";
            if (lower.endsWith(".js")) return "application/javascript; charset=utf-8";
            if (lower.endsWith(".png")) return "image/png";
            if (lower.endsWith(".jpg") || lower.endsWith(".jpeg")) return "image/jpeg";
            if (lower.endsWith(".svg")) return "image/svg+xml";
            if (lower.endsWith(".json")) return "application/json; charset=utf-8";
            if (lower.endsWith(".txt")) return "text/plain; charset=utf-8";
            return "application/octet-stream";
        }
    }
}
